branch-defaults:
  master:
    environment: Mbys-env
environment-defaults:
  Mbys-env:
    branch: null
    repository: null
global:
  application_name: mbys
  default_ec2_keyname: aws-eb
  default_platform: Python 3.12 running on 64bit Amazon Linux 2023
  default_region: eu-north-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
